### ISSUE TITLE
NoClassDefFoundError: com/android/build/gradle/AppPlugin

### ISSUE THREAD

**Issue by Airsaid** [autonomousapps/blog-gradle-all-the-way-down#1]
Hi, Tony!

I tried adding AGP code to `MeaningOfLifePlugin`:
```kotlin
class MeaningOfLifePlugin : Plugin<Project> {
  override fun apply(project: Project) {
    val appPlugin = project.plugins.findPlugin(AppPlugin::class.java)
    ......
}
```
Then I try to run the `AndroidSpec` test, but I get that error:
```
java.lang.NoClassDefFoundError: com/android/build/gradle/AppPlugin
	at mutual.aid.MeaningOfLifePlugin.apply(MeaningOfLifePlugin.kt:11)
	at mutual.aid.MeaningOfLifePlugin.apply(MeaningOfLifePlugin.kt:7)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:137)
	......
```
My IDEA version is: `IntelliJ IDEA 2021.3.2 (Ultimate Edition)`.

**Comment by autonomousapps** [comment]
I get a much weirder error when I try what you've done:
```Caused by: org.gradle.api.InvalidUserDataException: Cannot add a configuration with name 'androidJdkImage' as a configuration with that name already exists.```

But, note that the specs already apply an Android plugin:
```
plugins {
  // No version! One way or the other, the versions comes from the root project
  id 'com.android.library'
  id 'mutual.aid.meaning-of-life'
}
```
so if you try to apply one again from meaning-of-life, that will break. I'm not sure what your goal is, but if you're just playing around with configuring Android, try this instead:
```kotlin
pluginManager.withPlugin("com.android.library") {
  // configure an android library project here
}
```

**Comment by Airsaid** [comment]
Thanks for your quick reply! I re-read the source code and found that it was caused by the `useBuildScriptForAgp` parameter being false, resulting in no relevant path in the classpath. It was a problem with my usage and actually worked fine.

**Comment by autonomousapps** [comment]
Great, glad you were able to figure it out! 

On March 26, 2022, GitHub ***@***.***> wrote:
> Thanks for your quick reply! I re-read the source code and found that
> it was caused by the useBuildScriptForAgp parameter being false,
> resulting in no relevant path in the classpath. It was a problem with
> my usage and actually worked fine.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/blog-gradle-all-the-way-
down/issues/1#issuecomment-1079818332>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PM7CF6LCLS3YASCCCTVB7A2LANCNFSM5RRFOBRQ>.
You are receiving this because you commented.Message ID:
<autonomousapps/blog-gradle-all-the-way-
***@***.***>

**Comment by Rodrigolmti** [comment]
> 

In my case your answer solved, thanks.
